### ISSUE TITLE
[Feature Request] Add Autoscroll and Fingerprint lock

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomi#9]
Autoscroll will make Tachiyomi scroll pages for manga automatically after a time interval. 

Both features are available in TachiyomiEh (maintained by Nulldev/Nerdnumber 9), I included example in screenshots

https://github.com/NerdNumber9/TachiyomiEH/

![viber_image_2019-12-11_04-23-51](https://user-images.githubusercontent.com/34897862/70608792-be693400-1bce-11ea-8e3d-c0cf70feffe2.jpg)
![viber_image_2019-12-11_04-24-2](https://user-images.githubusercontent.com/34897862/70608793-bf01ca80-1bce-11ea-8bbb-978c2ea9a500.jpg)

**Comment by Jays2Kings** [comment]
Sorry to say but I don't think I'll be adding either of those features (soon at least):
* I can't really see a reason to add auto scroll as it doesn't seem to be something useful in regular tachiyomi vs tachiyomiEH
* tachiyomiEH is now using a deprecated version of the fingerprint scanner so I rather not try to bring that code into this fork (which wouldn't be a clean process with how different the 2 forks are). I don't think I'll be getting in that feature soon since I'd have to start from the ground up, but it would still be a nice feature

**Comment by joseph619** [comment]
I see, that's perfectly fine for now, I don't care much about the autoscroll but do add the fingerprint lock when you can (your version of course, TachiEh was just an example).
